name: Build on branch

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        branch: [v2.2.0, v2.2.1]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\msys2_github\
        update: true
        install: >-
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-meson
            git
            base-devel
            autotools
        msystem: MINGW64
        path-type: strict
    - name: build
      shell: msys2 {0}
      run: |
        export HOME=${{ github.workspace }}
        export LDFLAGS="-static -static-libgcc -static-libstdc++ -s"
        export CFLAGS="-flto"
        export CXXFLAGS="$CFLAGS"
        git clone --depth 1 -b ${{ matrix.branch }} https://gitlab.com/AOMediaCodec/SVT-AV1.git
        cd SVT-AV1
        mkdir binary
        cd binary && cmake .. -G 'Ninja' -D BUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release
        ninja
    - name: postprocessing
      shell: cmd
      run: |
        copy /y SVT-AV1\Bin\Release\SvtAv1EncApp.exe SvtAv1EncApp.exe
        copy /y SVT-AV1\LICENSE.md LICENSE.md
        copy /y SVT-AV1\PATENTS.md PATENTS.md
        7z a "SVT-AV1_${{ matrix.branch }}.7z" SvtAv1EncApp.exe LICENSE.md PATENTS.md
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: SVT-AV1
        path: |
          SVT-AV1_*.7z

  create_release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v3
      with:
        name: SVT-AV1
        path: artifacts
    
    - name: Get Date
      id: get_date
      run: |
        DATE_TIME=`date +'%Y-%m-%d-%H-%M-%S'`
        echo "DATE_TIME=${DATE_TIME}" >> $GITHUB_OUTPUT        
    # https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds
    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=build-${{ steps.get_date.outputs.DATE_TIME }}
        assets=()
        for asset in ${{ github.workspace }}/artifacts/*.7z; do
          assets+=("$asset")
        done
        gh release create "$TAG_NAME" "${assets[@]}"
        
